"""Stage 3 - Assembly, hyperlinking & house formatting.

Deterministic templating. Because the skeleton is code (not a prompt), every
article comes out with the exact same section order, table shape, and link
placement. The LLM fills sections; this file arranges them.
"""
from __future__ import annotations

from .schema import GeneratedSections, ResearchBundle, ToolProfile

SMALL = {"a", "an", "and", "or", "for", "the", "to", "of", "in", "on", "with"}


def _titlecase(s: str) -> str:
    words = s.split()
    return " ".join(
        w.capitalize() if (i == 0 or w.lower() not in SMALL) else w.lower()
        for i, w in enumerate(words)
    )


def _link(text: str, url: str | None) -> str:
    return f"[{text}]({url})" if url else text


def _ratings_line(t: ToolProfile) -> str:
    parts = []
    if t.g2_rating:
        parts.append(f"G2: {_link(t.g2_rating, t.g2_url)}")
    if t.capterra_rating:
        parts.append(f"Capterra: {_link(t.capterra_rating, t.capterra_url)}")
    return " | ".join(parts) if parts else "Ratings not found"


def _tool_section(t: ToolProfile) -> str:
    one_liner = t.one_liner
    if t.url and t.name in one_liner:               # link first mention of the name
        one_liner = one_liner.replace(t.name, _link(t.name, t.url), 1)

    lines = [f"### {t.name}", "", one_liner, "", "**What it does well**", ""]
    lines += [f"- {s}" for s in t.strengths]
    lines += ["", "**Where it has gaps**", ""]
    lines += [f"- {g}" for g in t.gaps]
    lines += [
        "",
        f"**Pricing:** {_link(t.pricing, t.pricing_url)}",
        "",
        f"**Ratings:** {_ratings_line(t)}",
        "",
        f"**Best for:** {t.best_for}",
        "",
    ]
    return "\n".join(lines)


def run(bundle: ResearchBundle, sec: GeneratedSections, house_style: dict) -> str:
    cat = bundle.category_label
    aud = bundle.audience
    n = len(bundle.tools)

    # --- frontmatter -------------------------------------------------------- #
    base = house_style.get("canonical_base", "https://example.com/blog/")
    md = [
        "---",
        f"title: {sec.title}",
        f"meta_description: {sec.meta_description}",
        f"slug: {sec.slug}",
        f"canonical: {base}{sec.slug}",
        f"primary_keyword: {bundle.primary_keyword}",
        f"generated_by: listicle-pipeline ({bundle.mode}, {bundle.model or 'n/a'})",
        "---",
        "",
        f"# {sec.title}",
        "",
        sec.intro_md,
        "",
    ]

    # --- quick comparison table -------------------------------------------- #
    md += [f"## Quick comparison: best {cat} for {aud}", "",
           "| Tool | Best for | Starting price | G2 rating |",
           "| --- | --- | --- | --- |"]
    for t in bundle.tools:
        name = _link(t.name, t.url)
        price = _link(t.pricing, t.pricing_url)
        g2 = _link(t.g2_rating, t.g2_url) if t.g2_rating else "-"
        best = t.best_for.replace("|", "/")
        md.append(f"| {name} | {best} | {price} | {g2} |")
    md.append("")

    # --- per-tool sections -------------------------------------------------- #
    md += [f"## The {n} best {cat} for {aud}", ""]
    md += [_tool_section(t) for t in bundle.tools]

    # --- buyer's guide (rendered straight from approved dimensions) -------- #
    md += [f"## What to look for in {cat} for {aud}", "",
           "Weigh these by which failure mode would hurt your program first.", ""]
    for d in bundle.dimensions:
        md += [f"**{_titlecase(d.name)}**", "", d.why, ""]

    # --- FAQ ---------------------------------------------------------------- #
    md += [f"## Questions people ask about {cat}", "", sec.faq_md, ""]

    # --- CTA / footer ------------------------------------------------------- #
    cta = house_style.get("cta_markdown", "")
    if cta:
        md += [cta, ""]
    md += ["---",
           f"*Draft generated by the listicle pipeline ({bundle.mode} mode). "
           "Verify pricing and ratings against the cited sources before publishing.*"]
    return "\n".join(md) + "\n"
